### ISSUE TITLE
Just a request for a Education Edition port

### ISSUE THREAD

**Issue by ghost** [Mario3264/WorldOfChemistry#6]
I love your mod and I wanted to suggest something I would love if you made Element
Constructor, Compound Creator, Lab Table, and Material Reducer craftable I hated that if you play on survival it is impossible to get lab equipment

**Comment by Mario0051** [comment]
Well it is outside the scope of this mod as they are not craftable in Education Edition, but a CraftTweaker script can make them craftable if wanted. I have not implemented these blocks yet either, but I hope I can get them implemented soon. I think I may update this mod to 1.14.3 Forge and see what I can do.

**Comment by ghost** [comment]
Okay, thank you also I wanted to ask is this mod gonna be in Minecraft 1.7.10 or is it quite impossible

**Comment by Mario0051** [comment]
I have no plans for backporting it to 1.7.10, it would also be much harder to do most things that I have already done in the current version.
